# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup}).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }]})
#   Character.create(name: 'Luke', movie: movies.first})

Player.create({name: "mills_g", alive: 1, kills: 0})
Player.create({name: "besh_j", alive: 1, kills: 0})
Player.create({name: "lowe_l", alive: 1, kills: 0})
Player.create({name: "guasco_a", alive: 1, kills: 0})
Player.create({name: "nitzan_l", alive: 1, kills: 0})
Player.create({name: "jones_b", alive: 1, kills: 0})
Player.create({name: "norton_d", alive: 1, kills: 0})
Player.create({name: "johnson_t", alive: 1, kills: 0})
Player.create({name: "anthony_j", alive: 1, kills: 0})
Player.create({name: "mendenhall_l", alive: 1, kills: 0})
Player.create({name: "eklund_j", alive: 1, kills: 0})
Player.create({name: "landau_j", alive: 1, kills: 0})
Player.create({name: "thomas_l", alive: 1, kills: 0})
Player.create({name: "jones_g", alive: 1, kills: 0})
Player.create({name: "batley_m", alive: 1, kills: 0})
Player.create({name: "springate_h", alive: 1, kills: 0})
Player.create({name: "carr_c", alive: 1, kills: 0})
Player.create({name: "jenkins_s", alive: 1, kills: 0})
Player.create({name: "collins_s", alive: 1, kills: 0})
Player.create({name: "wesselman_b", alive: 1, kills: 0})
Player.create({name: "otey_c", alive: 1, kills: 0})
Player.create({name: "kabsikalian_l", alive: 1, kills: 0})
Player.create({name: "selden_j", alive: 1, kills: 0})
Player.create({name: "anderson_a", alive: 1, kills: 0})
Player.create({name: "walker_j", alive: 1, kills: 0})
Player.create({name: "nelson_k", alive: 1, kills: 0})
Player.create({name: "lutze_t", alive: 1, kills: 0})
Player.create({name: "laidig_g", alive: 1, kills: 0})
Player.create({name: "syed_r", alive: 1, kills: 0})
Player.create({name: "waite_m", alive: 1, kills: 0})
Player.create({name: "biehler_m", alive: 1, kills: 0})
Player.create({name: "gullet_h", alive: 1, kills: 0})
Player.create({name: "nieske_n", alive: 1, kills: 0})
Player.create({name: "hurtado_j", alive: 1, kills: 0})
Player.create({name: "reulbach_z", alive: 1, kills: 0})
Player.create({name: "jeter_m", alive: 1, kills: 0})
Player.create({name: "stamey_c", alive: 1, kills: 0})
Player.create({name: "mckinsey_m", alive: 1, kills: 0})
Player.create({name: "hall_h", alive: 1, kills: 0})
Player.create({name: "johnson_m", alive: 1, kills: 0})
Player.create({name: "hilbish_s", alive: 1, kills: 0})
Player.create({name: "vance_s", alive: 1, kills: 0})
Player.create({name: "lods_j", alive: 1, kills: 0})
Player.create({name: "thillet_m", alive: 1, kills: 0})
Player.create({name: "koch_m", alive: 1, kills: 0})
Player.create({name: "cooke_r", alive: 1, kills: 0})
Player.create({name: "leclair_r", alive: 1, kills: 0})
Player.create({name: "hnilica_m", alive: 1, kills: 0})
Player.create({name: "parks_a", alive: 1, kills: 0})
Player.create({name: "godino_j", alive: 1, kills: 0})
Player.create({name: "collins_p", alive: 1, kills: 0})
Player.create({name: "casey_i", alive: 1, kills: 0})
Player.create({name: "stilphen_m", alive: 1, kills: 0})
Player.create({name: "fisher_g", alive: 1, kills: 0}) 
Player.create({name: "edwards_s", alive: 1, kills: 0})
Player.create({name: "tracy_b", alive: 1, kills: 0})
Player.create({name: "sun_d", alive: 1, kills: 0})
Player.create({name: "bragg_c", alive: 1, kills: 0})
Player.create({name: "cleveland_e", alive: 1, kills: 0})
Player.create({name: "fisk_k", alive: 1, kills: 0})
Player.create({name: "trufant_r", alive: 1, kills: 0})
Player.create({name: "sirimilla_n", alive: 1, kills: 0})
Player.create({name: "cooksey_a", alive: 1, kills: 0})
Player.create({name: "peterson_c", alive: 1, kills: 0})
Player.create({name: "kozlowski_l", alive: 1, kills: 0})
Player.create({name: "grissom_k", alive: 1, kills: 0})
Player.create({name: "grissom_s", alive: 1, kills: 0})
Player.create({name: "kramer_g", alive: 1, kills: 0})
Player.create({name: "holland_s", alive: 1, kills: 0})
Player.create({name: "hurley_d", alive: 1, kills: 0})
Player.create({name: "morrison_a", alive: 1, kills: 0})
Player.create({name: "zandhuis_w", alive: 1, kills: 0})
Player.create({name: "wyatt_a", alive: 1, kills: 0})